# -*- coding: utf-8 -*-
"""implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GxJsrMuO0XUhzAc5naqB6v8tfi64khA

# Importing baseline English training data - circa-data.tsv & SWDA_IA_Train_data.xlsx
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

# Enter the path to parent of the "data" folder
# FILE_PATH = '/content/drive/MyDrive/GMU/NLP/CS678Project'
FILE_PATH = '/content/drive/MyDrive/CS678'

"""##CIRCA data"""

df_circa = pd.read_csv(f'{FILE_PATH}/data/train_dataset/circa-data.tsv', sep='\t')

df_circa.head()

# Mapping the values in circa-data.tsv to standardised values (provided in the paper)
circa_value_mapping = {
    'Yes': 'yes',
    'No': 'no',
    'Yes, subject to some conditions': 'yes',
    'In the middle, neither yes nor no': 'middle',
    'Other': None,  # Set to None for now, to filter out later
    'N/A': None  # Set to None for now, to filter out later
}

df_circa['goldstandard2'] = df_circa['goldstandard2'].map(circa_value_mapping)
df_circa = df_circa.dropna(subset=['goldstandard2'])

# Creating the input column by simply adding question and answer columns (approach proposed in the paper)
df_circa['text_input'] = df_circa['question-X'] + " " + df_circa['answer-Y']

df_circa_final = df_circa[['text_input', 'goldstandard2']]
df_circa_final = df_circa_final.rename(columns={'goldstandard2': 'label'})

# This now, is the test data for circa-data.tsv -> x = text_input, y = labe;
df_circa_final.head()

"""## SWDA data"""

df_swda = pd.read_excel(f'{FILE_PATH}/data/train_dataset/SWDA_IA_Train_data.xlsx')

df_swda.head()

df_swda['t1_label'].unique()

df_swda['t2_label'].unique()

# Mapping the values in SWDA_IA_Train_data.xlsx to standardised values (provided in the paper)
swda_value_mapping = {
    'yes': 'yes',
    'no': 'no',
    'pyes': 'yes',
    'pno': 'no',
    'middle': 'middle'
}

df_swda['t2_label'] = df_swda['t2_label'].map(swda_value_mapping)
# df_swda = df_swda.dropna(subset=['t2_label'])

"""Similar to circa, we combien question and answer to create the input column"""

df_swda['text_input'] = df_swda['questions_raw'] + " " + df_swda['answer']

df_swda_final = df_swda[['text_input', 't2_label']]

df_swda_final = df_swda_final.rename(columns={'t2_label': 'label'})

df_swda_final.head()

"""Now, I have two dataframes -> df_circa_final and df_swda_final"""

df_swda_final.head()

"""## Creating the final english dataset"""

df_english = pd.concat([df_circa_final, df_swda_final], axis = 0)

df_english.head()

"""## Setting up the model, training, and testing procedures"""

import torch
torch.cuda.empty_cache()

# Confirm that the GPU is detected

assert torch.cuda.is_available()

# Get the GPU device name.
device_name = torch.cuda.get_device_name()
n_gpu = torch.cuda.device_count()
print(f"Found device: {device_name}, n_gpu: {n_gpu}")
device = torch.device("cuda")

import random
import numpy as np
import torch

def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

seed_everything()

# Mapping various labels across all the datasets to standardized 0, 1, and 2 (for multiclass classification)
label_mapping = {'yes': 0, 'no': 1, 'middle': 2, 0: 0, 1: 1, 2: 2}

# A function the simply creates inputs for our model - Utlizes the XLMRobertaTokenizer present in helpers.py
from helpers import tokenize_and_format, flat_accuracy
import pandas as pd
import numpy as np

def create_tensors_and_text(df, shuffle=False):
  # returns input_ids, attention_masks, labels
  seed_everything()


  if shuffle:
    df = df.sample(frac=1).reset_index(drop=True)

  texts = df.text_input.values
  labels = df.label.values

  input_ids, attention_masks = tokenize_and_format(texts)

  label_list = []
  for l in labels:
    label_array = np.zeros(len(set(labels)))
    # label_array[int(l)-1] = 1
    label_array[int(label_mapping[l])] = 1
    label_list.append(label_array)

  # Convert the lists into tensors.
  input_ids = torch.cat(input_ids, dim=0)
  attention_masks = torch.cat(attention_masks, dim=0)
  labels = torch.tensor(np.array(label_list))

  # Print sentence 0, now as a list of IDs.
  print('Original: ', texts[0])
  print('Token IDs:', input_ids[0])

  return input_ids, attention_masks, labels

# Receive the appropriate tensors and split them into train, val, and test sets
english_input_ids, english_attention_masks, english_labels = create_tensors_and_text(df_english, True)
english_texts = df_english.text_input.values

seed_everything()

total = len(df_english)

num_train = int(total * .8)
num_val = total - num_train

english_train_set = [(english_input_ids[i], english_attention_masks[i], english_labels[i]) for i in range(num_train)]
english_val_set = [(english_input_ids[i], english_attention_masks[i], english_labels[i]) for i in range(num_train, num_val+num_train)]

english_train_text = [english_texts[i] for i in range(num_train)]
english_val_text = [english_labels[i] for i in range(num_train, num_val+num_train)]

"""<h2>Declaring the model and an optimizer as proposed in the paper</h2>"""

from transformers import XLMRobertaForSequenceClassification, Trainer, TrainingArguments

model = XLMRobertaForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=3)
model.cuda()

from torch.optim import AdamW

batch_size = 8
optimizer = torch.optim.AdamW(model.parameters(), lr=9e-5)
epochs = 3

# 0.0003

# function to get validation f1 score - returns f1_score, validation_accuracy
from sklearn.metrics import f1_score
def get_validation_performance(val_set):
    # Put the model in evaluation mode
    model.eval()

    # Tracking variables
    total_eval_accuracy = 0
    total_eval_loss = 0

    num_batches = int(len(val_set)/batch_size) + 1

    total_correct = 0
    # These lists will store all the predictions and true labels across batches
    all_predictions = []
    all_labels = []

    for i in range(num_batches):

      end_index = min(batch_size * (i+1), len(val_set))

      batch = val_set[i*batch_size:end_index]

      if len(batch) == 0: continue

      input_id_tensors = torch.stack([data[0] for data in batch])
      input_mask_tensors = torch.stack([data[1] for data in batch])
      label_tensors = torch.stack([data[2] for data in batch])

      # Move tensors to the GPU
      b_input_ids = input_id_tensors.to(device)
      b_input_mask = input_mask_tensors.to(device)
      b_labels = label_tensors.to(device)

      # Tell pytorch not to bother with constructing the compute graph during
      # the forward pass, since this is only needed for backprop (training).
      with torch.no_grad():

        # Forward pass, calculate logit predictions.
        # Note: this line of code might need to change depending on the model
        # the current line will work for bert-base-uncased
        # please refer to huggingface documentation for other models
        outputs = model(b_input_ids,
                                token_type_ids=None,
                                attention_mask=b_input_mask,
                                labels=b_labels)
        loss = outputs.loss
        logits = outputs.logits

        # Accumulate the validation loss.
        total_eval_loss += loss.item()

        # Move logits and labels to CPU
        logits = (logits).detach().cpu().numpy()
        label_ids = b_labels.to('cpu').numpy()


        # Calculate the number of correctly labeled examples in batch
        pred_flat = np.argmax(logits, axis=1).flatten()
        labels_flat = np.argmax(label_ids, axis=1).flatten()

        all_predictions.extend(pred_flat)
        all_labels.extend(labels_flat)

        num_correct = np.sum(pred_flat == labels_flat)
        total_correct += num_correct

    # Report the final accuracy for this validation run.
    print("Num of correct predictions =", total_correct)
    avg_val_accuracy = total_correct / len(val_set)
    f1 = f1_score(all_labels, all_predictions, average='weighted')
    return f1,avg_val_accuracy

# Function the run training loops while optimizing AdamW (gradient descent)

import random

def run_training_loops(train_set, val_set, epochs):
  # training loop
  val_acc = 0
  # For each epoch...
  for epoch_i in range(0, epochs):
      # Perform one full pass over the training set.

      print("")
      print('======== Epoch {:} / {:} ========'.format(epoch_i + 1, epochs))
      print('Training...')

      # Reset the total loss for this epoch.
      total_train_loss = 0

      # Put the model into training mode.
      model.train()

      # For each batch of training data...
      num_batches = int(len(train_set)/batch_size) + 1

      for i in range(num_batches):
        end_index = min(batch_size * (i+1), len(train_set))

        batch = train_set[i*batch_size:end_index]

        if len(batch) == 0: continue

        input_id_tensors = torch.stack([data[0] for data in batch])
        input_mask_tensors = torch.stack([data[1] for data in batch])
        label_tensors = torch.stack([data[2] for data in batch])

        # Move tensors to the GPU
        b_input_ids = input_id_tensors.to(device)
        b_input_mask = input_mask_tensors.to(device)
        b_labels = label_tensors.to(device)

        optimizer.zero_grad()

        # Perform a forward pass (evaluate the model on this training batch).
        # this line of code might need to change depending on the model
        outputs = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask, labels=b_labels)

        loss = outputs.loss
        logits = outputs.logits

        total_train_loss += loss.item()

        # Perform a backward pass to calculate the gradients.
        loss.backward()

        # Update parameters and take a step using the computed gradient.
        optimizer.step()

      # ========================================
      #               Validation
      # ========================================
      # After the completion of each training epoch, measure our performance on
      # our validation set. Implement this function in the cell above.
      print(f"Total loss: {total_train_loss}")
      f1,val_acc = get_validation_performance(val_set)
      print(f"Validation accuracy: {val_acc}")

  print("")
  print("Training complete!")
  return val_acc

  # TODO: SAVE YOUR MODEL HERE... (Refer PyTorch documentation for how to save models)
  # torch.save(model.state_dict(), './saved_model_fixed_labels')

run_training_loops(english_train_set, english_val_set, 10)

torch.save(model.state_dict(), './english_model')

# Function that takes a dataframe, and outputs a modified version of it
# The version that will be used for training, validation, and testing purposes
def create_file(df):
  def map_labels(label):
      label = label.lower()
      if label in ['y', 'py', 'yes']:
          return 0
      elif label in ['n', 'pn', 'no']:
          return 1
      elif label in ['uk', 'middle', 'unk', 'unkwn', 'm', 'maybe']:
          return 2

  df['label'] = df['label'].apply(map_labels)
  df['text_input'] = df['question'] + " " + df['answer']
  df = df[['text_input', 'label']]
  df = df.dropna()
  return df

"""#  Recreating Experiment 5.1 Cross-Lingual Learning from English
The results of the said experiment being performed below are included in Section 3.3 Results under Table 1 Results (F1) obtained with XLM-RoBERTa when trained with Circa and SWDA-IA in the project report.

## Hindi
"""

df_hindi = pd.read_csv(f'{FILE_PATH}/data/test_dataset/hindi_test_dataset.csv')
df_hindi = create_file(df_hindi)

df_hindi.head()

hindi_input_ids, hindi_attention_masks, hindi_labels = create_tensors_and_text(df_hindi, False)
hindi_texts = df_hindi.text_input.values

seed_everything()

total = len(df_hindi)

hindi_test_set = [(hindi_input_ids[i], hindi_attention_masks[i], hindi_labels[i]) for i in range(total)]

hindi_test_text = [hindi_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(hindi_test_set)[0]

"""## Korean"""

# Korean

df_korean = pd.read_csv(f'{FILE_PATH}/data/test_dataset/korean_test_dataset.csv')
df_korean = create_file(df_korean)

korean_input_ids, korean_attention_masks, korean_labels = create_tensors_and_text(df_korean, False)
korean_texts = df_korean.text_input.values

seed_everything()

total = len(df_korean)

korean_test_set = [(korean_input_ids[i], korean_attention_masks[i], korean_labels[i]) for i in range(total)]

korean_test_text = [korean_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(korean_test_set)[0]

"""## Chinese"""

# chinese

df_chinese = pd.read_csv(f'{FILE_PATH}/data/test_dataset/chinese_test_dataset.csv')
df_chinese = create_file(df_chinese)

chinese_input_ids, chinese_attention_masks, chinese_labels = create_tensors_and_text(df_chinese, False)
chinese_texts = df_chinese.text_input.values

seed_everything()

total = len(df_chinese)

chinese_test_set = [(chinese_input_ids[i], chinese_attention_masks[i], chinese_labels[i]) for i in range(total)]

chinese_test_text = [chinese_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(chinese_test_set)[0]

"""## Bangla"""

# bangla

df_bangla = pd.read_csv(f'{FILE_PATH}/data/test_dataset/bangla_test_dataset.csv')
df_bangla = create_file(df_bangla)

bangla_input_ids, bangla_attention_masks, bangla_labels = create_tensors_and_text(df_bangla, False)
bangla_texts = df_bangla.text_input.values

seed_everything()

total = len(df_bangla)

bangla_test_set = [(bangla_input_ids[i], bangla_attention_masks[i], bangla_labels[i]) for i in range(total)]

bangla_test_text = [bangla_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(bangla_test_set)[0]

"""## Turkish"""

# turkish

df_turkish = pd.read_csv(f'{FILE_PATH}/data/test_dataset/turkish_test_dataset.csv')
df_turkish = create_file(df_turkish)

turkish_input_ids, turkish_attention_masks, turkish_labels = create_tensors_and_text(df_turkish, False)
turkish_texts = df_turkish.text_input.values

seed_everything()

total = len(df_turkish)

turkish_test_set = [(turkish_input_ids[i], turkish_attention_masks[i], turkish_labels[i]) for i in range(total)]

turkish_test_text = [turkish_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(turkish_test_set)[0]

"""## Spanish"""

# spanish

df_spanish = pd.read_csv(f'{FILE_PATH}/data/test_dataset/spanish_test_dataset.csv')
df_spanish = create_file(df_spanish)

spanish_input_ids, spanish_attention_masks, spanish_labels = create_tensors_and_text(df_spanish, False)
spanish_texts = df_spanish.text_input.values

seed_everything()

total = len(df_spanish)

spanish_test_set = [(spanish_input_ids[i], spanish_attention_masks[i], spanish_labels[i]) for i in range(total)]

spanish_test_text = [spanish_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(spanish_test_set)[0]

"""## Nepali"""

# nepali

df_nepali = pd.read_csv(f'{FILE_PATH}/data/test_dataset/nepali_test_dataset.csv')
df_nepali = create_file(df_nepali)

nepali_input_ids, nepali_attention_masks, nepali_labels = create_tensors_and_text(df_nepali, False)
nepali_texts = df_nepali.text_input.values

seed_everything()

total = len(df_nepali)

nepali_test_set = [(nepali_input_ids[i], nepali_attention_masks[i], nepali_labels[i]) for i in range(total)]

nepali_test_text = [nepali_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(nepali_test_set)[0]

"""## Persian"""

# persian

df_persian = pd.read_csv(f'{FILE_PATH}/data/test_dataset/persian_test_dataset.csv')
df_persian = create_file(df_persian)

persian_input_ids, persian_attention_masks, persian_labels = create_tensors_and_text(df_persian, False)
persian_texts = df_persian.text_input.values

seed_everything()

total = len(df_persian)

persian_test_set = [(persian_input_ids[i], persian_attention_masks[i], persian_labels[i]) for i in range(total)]

persian_test_text = [persian_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(persian_test_set)[0]

"""# Experiment 5.2 Fine-Tuning with the New Language

The results of the said experiment being performed below are included in Section 3.3 Results under Table 2 Results obtained in multiple languages with
XLM-RoBERTa, trained blending with English corpora in the project report.

## Setting up the model, optimizer and training function

<h3>The training strategy</h3>
<p>Concatenate English data with the other language, at every epoch, take some of the other language's row off (determined by alpha).</p>

<p>You will notice the parameters as "train_set_english" and the other language as "train_set_other_language" which is the other language data set to be concatenated. This function works for every language. Just pass in the appropriate parameter (train set)</p>

<p>This is what the process looks like (for every language)<p>
<ol>
<li>Import the test, train, and validation files</li>
<li>Create tensors and split the data into train, test, and val</li>
<li>Call run_training_loops_new_strategy()</li>
</ol>
"""

from transformers import XLMRobertaForSequenceClassification, Trainer, TrainingArguments

model = XLMRobertaForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=3)
model.cuda()

from torch.optim import AdamW

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 30

# 0.0003

import random
import torch

def run_training_loops_new_strategy(train_set_english, train_set_other_language, val_set, epochs, alpha):
    # Assuming train_set_english and train_set_other_language are lists of tuples (input_id, attention_mask, label)
    # and alpha is the reduction factor for the other_language dataset size after each epoch.

    val_acc = 0  # Initialize validation accuracy

    for epoch_i in range(epochs):
        print(f"\n======== Epoch {epoch_i + 1} / {epochs} ========")
        print("Training...")

        # Concatenate English data with a subset of other_language data
        # Reduce the other_language dataset by alpha after each epoch
        other_language_data_size = int(len(train_set_other_language) * (alpha ** epoch_i))
        current_train_set = train_set_english + random.sample(train_set_other_language, other_language_data_size)

        total_train_loss = 0  # Reset total loss for this epoch

        model.train()  # Put the model into training mode

        num_batches = len(current_train_set) // batch_size + (len(current_train_set) % batch_size != 0)

        for i in range(num_batches):
            batch = current_train_set[i * batch_size:(i + 1) * batch_size]
            if not batch:
                continue

            b_input_ids, b_input_mask, b_labels = zip(*batch)  # Unpack batch data

            # Convert lists to tensors and move them to the device (GPU/CPU)
            b_input_ids = torch.stack(b_input_ids).to(device)
            b_input_mask = torch.stack(b_input_mask).to(device)
            b_labels = torch.stack(b_labels).to(device)

            optimizer.zero_grad()

            outputs = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask, labels=b_labels)
            loss = outputs.loss
            total_train_loss += loss.item()

            loss.backward()  # Calculate gradients
            optimizer.step()  # Update parameters

        print(f"Total loss: {total_train_loss}")
        f1,val_acc = get_validation_performance(val_set)  # Evaluate on validation set
        print(f"Validation accuracy: {val_acc}")

    print("\nTraining complete!")
    return val_acc

# Note: You would need to define `get_validation_performance`, `batch_size`, `model`, `optimizer`, and ensure that `device` is set correctly (e.g., to 'cuda' or 'cpu').
# Also, ensure that your model, optimizer, and data are correctly transferred to the GPU if you're using one.

# Lastly, saving the model after training is completed is essential for later use or further training.
# The placeholder for saving the model is already in your script, so don't forget to use it with your model's and training's specifics.

"""## Hindi dataset"""

df_hindi_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/hindi_test_dataset.csv')
df_hindi_test = create_file(df_hindi_test)

df_hindi_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/hindi_dev_dataset.csv')
df_hindi_val = create_file(df_hindi_val)

df_hindi_train_yes = pd.read_excel(f'{FILE_PATH}/data/train_dataset/hindi_yes_answer.xlsx')
df_hindi_train_yes = create_file(df_hindi_train_yes)

df_hindi_train_no = pd.read_excel(f'{FILE_PATH}/data/train_dataset/hindi_no_answer.xlsx')
df_hindi_train_no = create_file(df_hindi_train_no)

df_hindi_train = pd.concat([df_hindi_train_yes, df_hindi_train_no])

df_hindi_combined = pd.concat([df_hindi_test, df_hindi_val, df_hindi_train])

hindi_input_ids, hindi_attention_masks, hindi_labels = create_tensors_and_text(df_hindi_combined, False)
hindi_texts = df_hindi_combined.text_input.values

seed_everything()

len_test = len(df_hindi_test)
len_val = len(df_hindi_val)
len_train = len(df_hindi_train)

hindi_test_set = [(hindi_input_ids[i], hindi_attention_masks[i], hindi_labels[i]) for i in range(len_test)]
hindi_test_text = [hindi_labels[i] for i in range(len_test)]

hindi_val_set = [(hindi_input_ids[i], hindi_attention_masks[i], hindi_labels[i]) for i in range(len_test,len_test + len_val)]
hindi_val_text = [hindi_labels[i] for i in range(len_test,len_test + len_val)]

hindi_train_set = [(hindi_input_ids[i], hindi_attention_masks[i], hindi_labels[i]) for i in range(len_test + len_val, len(df_hindi_combined))]
hindi_train_text = [hindi_labels[i] for i in range(len_test + len_val, len(df_hindi_combined))]

len(english_train_set)

len(hindi_train_set)

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 3

# def run_training_loops_new_strategy(train_set_english, train_set_hindi, val_set, epochs, alpha, batch_size, optimizer)
run_training_loops_new_strategy(english_train_set, hindi_train_set, hindi_val_set, epochs=epochs, alpha=0.2)

# run_training_loops_new_strategy(english_train_set, hindi_train_set, hindi_val_set, epochs=1, alpha=0.87)

seed_everything()
get_validation_performance(hindi_test_set)[0]

"""## Korean dataset"""

df_korean_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/korean_test_dataset.csv')
df_korean_test = create_file(df_korean_test)

df_korean_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/korean_dev_dataset.csv')
df_korean_val = create_file(df_korean_val)

df_korean_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/korean_yes_answer.csv')
df_korean_train_yes['label'] = 'y'
df_korean_train_yes = create_file(df_korean_train_yes)

df_korean_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/korean_no_answer.csv')
df_korean_train_no['label'] = 'n'
df_korean_train_no = create_file(df_korean_train_no)

df_korean_train = pd.concat([df_korean_train_yes, df_korean_train_no])

df_korean_combined = pd.concat([df_korean_test, df_korean_val, df_korean_train])

korean_input_ids, korean_attention_masks, korean_labels = create_tensors_and_text(df_korean_combined, False)
korean_texts = df_korean_combined.text_input.values

seed_everything()

len_test = len(df_korean_test)
len_val = len(df_korean_val)
len_train = len(df_korean_train)

korean_test_set = [(korean_input_ids[i], korean_attention_masks[i], korean_labels[i]) for i in range(len_test)]
korean_test_text = [korean_labels[i] for i in range(len_test)]

korean_val_set = [(korean_input_ids[i], korean_attention_masks[i], korean_labels[i]) for i in range(len_test,len_test + len_val)]
korean_val_text = [korean_labels[i] for i in range(len_test,len_test + len_val)]

korean_train_set = [(korean_input_ids[i], korean_attention_masks[i], korean_labels[i]) for i in range(len_test + len_val, len(df_korean_combined))]
korean_train_text = [korean_labels[i] for i in range(len_test + len_val, len(df_korean_combined))]

len(korean_train_set)

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 10

run_training_loops_new_strategy(english_train_set, korean_train_set, korean_val_set, epochs=epochs, alpha=0.5)

seed_everything()
get_validation_performance(korean_test_set)[0]

"""## Chinese dataset"""

df_chinese_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/chinese_test_dataset.csv')
df_chinese_test = create_file(df_chinese_test)

df_chinese_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/chinese_dev_dataset.csv')
df_chinese_val = create_file(df_chinese_val)

df_chinese_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/chinese_naturalconv_yes_answer.csv')
# df_chinese_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/chinese_lccc_yes_answer.csv')
df_chinese_train_yes['label'] = 'y'
df_chinese_train_yes = create_file(df_chinese_train_yes)

df_chinese_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/chinese_naturalconv_no_answer.csv')
# df_chinese_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/chinese_lccc_no_answer.csv')
df_chinese_train_no['label'] = 'n'
df_chinese_train_no = create_file(df_chinese_train_no)

df_chinese_train = pd.concat([df_chinese_train_yes, df_chinese_train_no])

df_chinese_combined = pd.concat([df_chinese_test, df_chinese_val, df_chinese_train])

chinese_input_ids, chinese_attention_masks, chinese_labels = create_tensors_and_text(df_chinese_combined, False)
chinese_texts = df_chinese_combined.text_input.values

seed_everything()

len_test = len(df_chinese_test)
len_val = len(df_chinese_val)
len_train = len(df_chinese_train)

chinese_test_set = [(chinese_input_ids[i], chinese_attention_masks[i], chinese_labels[i]) for i in range(len_test)]
chinese_test_text = [chinese_labels[i] for i in range(len_test)]

chinese_val_set = [(chinese_input_ids[i], chinese_attention_masks[i], chinese_labels[i]) for i in range(len_test,len_test + len_val)]
chinese_val_text = [chinese_labels[i] for i in range(len_test,len_test + len_val)]

chinese_train_set = [(chinese_input_ids[i], chinese_attention_masks[i], chinese_labels[i]) for i in range(len_test + len_val, len(df_chinese_combined))]
chinese_train_text = [chinese_labels[i] for i in range(len_test + len_val, len(df_chinese_combined))]

len(chinese_train_set)

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 3

run_training_loops_new_strategy(english_train_set, chinese_train_set, chinese_val_set, epochs=epochs, alpha=0.2)

# run_training_loops_new_strategy(english_train_set, chinese_train_set, chinese_val_set, epochs=2, alpha=1)

seed_everything()
get_validation_performance(chinese_test_set)[0]

"""## Turkish dataset"""

df_turkish_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/turkish_test_dataset.csv')
df_turkish_test = create_file(df_turkish_test)

df_turkish_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/turkish_dev_dataset.csv')
df_turkish_val = create_file(df_turkish_val)

df_turkish_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/turkish_cqa_yes_answer.csv')
# df_turkish_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/turkish_faq_yes_answer.csv')
df_turkish_train_yes = create_file(df_turkish_train_yes)

df_turkish_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/turkish_cqa_no_answer.csv')
# df_turkish_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/turkish_faq_no_answer.csv')
df_turkish_train_no = create_file(df_turkish_train_no)

df_turkish_train = pd.concat([df_turkish_train_yes, df_turkish_train_no])

df_turkish_combined = pd.concat([df_turkish_test, df_turkish_val, df_turkish_train])

turkish_input_ids, turkish_attention_masks, turkish_labels = create_tensors_and_text(df_turkish_combined, False)
turkish_texts = df_turkish_combined.text_input.values

seed_everything()

len_test = len(df_turkish_test)
len_val = len(df_turkish_val)
len_train = len(df_turkish_train)

turkish_test_set = [(turkish_input_ids[i], turkish_attention_masks[i], turkish_labels[i]) for i in range(len_test)]
turkish_test_text = [turkish_labels[i] for i in range(len_test)]

turkish_val_set = [(turkish_input_ids[i], turkish_attention_masks[i], turkish_labels[i]) for i in range(len_test,len_test + len_val)]
turkish_val_text = [turkish_labels[i] for i in range(len_test,len_test + len_val)]

turkish_train_set = [(turkish_input_ids[i], turkish_attention_masks[i], turkish_labels[i]) for i in range(len_test + len_val, len(df_turkish_combined))]
turkish_train_text = [turkish_labels[i] for i in range(len_test + len_val, len(df_turkish_combined))]

len(turkish_train_set)

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 3

run_training_loops_new_strategy(english_train_set, turkish_train_set, turkish_val_set, epochs=epochs, alpha=0.2)

seed_everything()
get_validation_performance(turkish_test_set)[0]

"""## Spanish dataset"""

df_spanish_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/spanish_test_dataset.csv')
df_spanish_test = create_file(df_spanish_test)

df_spanish_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/spanish_dev_dataset.csv')
df_spanish_val = create_file(df_spanish_val)

df_spanish_train_yes = pd.read_excel(f'{FILE_PATH}/data/train_dataset/spanish_callfriend_yes_answer.xlsx')
# df_spanish_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/spanish_yes_answer.csv')
df_spanish_train_yes['label'] = 'y'
df_spanish_train_yes = create_file(df_spanish_train_yes)

df_spanish_train_no = pd.read_excel(f'{FILE_PATH}/data/train_dataset/spanish_callfriend_no_answer.xlsx')
# df_spanish_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/spanish_no_answer.csv')
df_spanish_train_no['label'] = 'n'
df_spanish_train_no = create_file(df_spanish_train_no)

df_spanish_train = pd.concat([df_spanish_train_yes, df_spanish_train_no])

df_spanish_combined = pd.concat([df_spanish_test, df_spanish_val, df_spanish_train])

spanish_input_ids, spanish_attention_masks, spanish_labels = create_tensors_and_text(df_spanish_combined, False)
spanish_texts = df_spanish_combined.text_input.values

seed_everything()

len_test = len(df_spanish_test)
len_val = len(df_spanish_val)
len_train = len(df_spanish_train)

spanish_test_set = [(spanish_input_ids[i], spanish_attention_masks[i], spanish_labels[i]) for i in range(len_test)]
spanish_test_text = [spanish_labels[i] for i in range(len_test)]

spanish_val_set = [(spanish_input_ids[i], spanish_attention_masks[i], spanish_labels[i]) for i in range(len_test,len_test + len_val)]
spanish_val_text = [spanish_labels[i] for i in range(len_test,len_test + len_val)]

spanish_train_set = [(spanish_input_ids[i], spanish_attention_masks[i], spanish_labels[i]) for i in range(len_test + len_val, len(df_spanish_combined))]
spanish_train_text = [spanish_labels[i] for i in range(len_test + len_val, len(df_spanish_combined))]

len(spanish_train_set)

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 3

run_training_loops_new_strategy(english_train_set, spanish_train_set, spanish_val_set, epochs=epochs, alpha=0.2)

seed_everything()
get_validation_performance(spanish_test_set)[0]

"""# Experiment 5.3 Fine-Tuning with Several Languages

<h3>The training strategy</h3>
<h2>This is very similar to experiment 5.2 but we combine multiple languages in an attempt to get better performances</h2>

<p>Concatenate English data with the other languages (the combinations that the paper proposed), at every epoch, take some of the other language's row off (determined by alpha).</p>

<p>You will notice the parameters as "train_set_english" and the other language as "train_set_other_language" which is the other language data set to be concatenated. This function works for every language. Just pass in the appropriate parameter (train set)</p>

<p>This is what the process looks like (for every language)<p>
<ol>
<li>Import the test, train, and validation files for the language</li>
<li>Import only the train data for every language that will be in the blend</li>
<li>Create a "super train" (we coined this by ourselves) dataset by combine test dataframe from the main language and the other languages in the blend</li>
<li>Create the final dataframe by combining the main language's test, val, and the super train files</li>
<li>Create tensors and split the data into train, test, and val</li>
<li>Call run_training_loops_new_strategy()</li>
</ol>

The results of the said experiment being performed below are included in Section 3.3 Results under Table 3 Results obtained with XLM-RoBERTa, trained blending with English corpora and the instances obtained with distant supervision in other languages. Here ∆ F1 represents the improvement of F1 score from Table 1 in the project report.

##Data Loading

Load all the datasets to reduce redundency.

Hindi datasets.
"""

df_hindi_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/hindi_test_dataset.csv')
df_hindi_test = create_file(df_hindi_test)

df_hindi_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/hindi_dev_dataset.csv')
df_hindi_val = create_file(df_hindi_val)

df_hindi_train_yes = pd.read_excel(f'{FILE_PATH}/data/train_dataset/hindi_yes_answer.xlsx')
df_hindi_train_yes = create_file(df_hindi_train_yes)

df_hindi_train_no = pd.read_excel(f'{FILE_PATH}/data/train_dataset/hindi_no_answer.xlsx')
df_hindi_train_no = create_file(df_hindi_train_no)

df_hindi_train = pd.concat([df_hindi_train_yes, df_hindi_train_no])

"""Chinese datasets."""

df_chinese_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/chinese_test_dataset.csv')
df_chinese_test = create_file(df_chinese_test)

df_chinese_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/chinese_dev_dataset.csv')
df_chinese_val = create_file(df_chinese_val)

df_chinese_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/chinese_naturalconv_yes_answer.csv')
# df_chinese_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/chinese_lccc_yes_answer.csv')
df_chinese_train_yes['label'] = 'y'
df_chinese_train_yes = create_file(df_chinese_train_yes)

df_chinese_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/chinese_naturalconv_no_answer.csv')
# df_chinese_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/chinese_lccc_no_answer.csv')
df_chinese_train_no['label'] = 'n'
df_chinese_train_no = create_file(df_chinese_train_no)

df_chinese_train = pd.concat([df_chinese_train_yes, df_chinese_train_no])

"""Korean datasets."""

df_korean_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/korean_test_dataset.csv')
df_korean_test = create_file(df_korean_test)

df_korean_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/korean_dev_dataset.csv')
df_korean_val = create_file(df_korean_val)

df_korean_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/korean_yes_answer.csv')
df_korean_train_yes['label'] = 'y'
df_korean_train_yes = create_file(df_korean_train_yes)

df_korean_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/korean_no_answer.csv')
df_korean_train_no['label'] = 'n'
df_korean_train_no = create_file(df_korean_train_no)

df_korean_train = pd.concat([df_korean_train_yes, df_korean_train_no])

"""Spanish datasets."""

df_spanish_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/spanish_test_dataset.csv')
df_spanish_test = create_file(df_spanish_test)

df_spanish_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/spanish_dev_dataset.csv')
df_spanish_val = create_file(df_spanish_val)

df_spanish_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/spanish_yes_answer.csv')
df_spanish_train_yes['label'] = 'y'
df_spanish_train_yes = create_file(df_spanish_train_yes)

df_spanish_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/spanish_no_answer.csv')
df_spanish_train_no['label'] = 'n'
df_spanish_train_no = create_file(df_spanish_train_no)

df_spanish_train = pd.concat([df_spanish_train_yes, df_spanish_train_no])

"""Turkish datasets."""

df_turkish_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/turkish_test_dataset.csv')
df_turkish_test = create_file(df_turkish_test)

df_turkish_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/turkish_dev_dataset.csv')
df_turkish_val = create_file(df_turkish_val)

df_turkish_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/turkish_cqa_yes_answer.csv')
# df_turkish_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/turkish_faq_yes_answer.csv')
df_turkish_train_yes = create_file(df_turkish_train_yes)

df_turkish_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/turkish_cqa_no_answer.csv')
# df_turkish_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/turkish_faq_no_answer.csv')
df_turkish_train_no = create_file(df_turkish_train_no)

df_turkish_train = pd.concat([df_turkish_train_yes, df_turkish_train_no])

"""We have 3 other languages : Nepali, Bangla and Persian datasets for which we do not have training data but just test and dev data. The training is based upon the other languages' training data.

Nepali dataset.
"""

df_nepali_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/nepali_test_dataset.csv')
df_nepali_test = create_file(df_nepali_test)

df_nepali_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/nepali_dev_dataset.csv')
df_nepali_val = create_file(df_nepali_val)

"""Bangla dataset."""

df_bangla_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/bangla_test_dataset.csv')
df_bangla_test = create_file(df_bangla_test)

df_bangla_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/bangla_dev_dataset.csv')
df_bangla_val = create_file(df_bangla_val)

"""Persian dataset."""

df_persian_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/persian_test_dataset.csv')
df_persian_test = create_file(df_persian_test)

df_persian_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/persian_dev_dataset.csv')
df_persian_val = create_file(df_persian_val)

"""##Hindi dataset

For Hindi dataset we need -> Hindi, Chinese and Spanish datasets.
"""

# Combination of the main language's train data (hindi) and the other languages in the blend (chinese & spanish)
df_hindi_super_train = pd.concat([df_hindi_train, df_chinese_train, df_spanish_train])

df_hindi_combined = pd.concat([df_hindi_test, df_hindi_val, df_hindi_super_train])

hindi_input_ids, hindi_attention_masks, hindi_labels = create_tensors_and_text(df_hindi_combined, False)
hindi_texts = df_hindi_combined.text_input.values

seed_everything()

len_test = len(df_hindi_test)
len_val = len(df_hindi_val)
len_train = len(df_hindi_super_train)

hindi_test_set = [(hindi_input_ids[i], hindi_attention_masks[i], hindi_labels[i]) for i in range(len_test)]
hindi_test_text = [hindi_labels[i] for i in range(len_test)]

hindi_val_set = [(hindi_input_ids[i], hindi_attention_masks[i], hindi_labels[i]) for i in range(len_test,len_test + len_val)]
hindi_val_text = [hindi_labels[i] for i in range(len_test,len_test + len_val)]

hindi_train_set = [(hindi_input_ids[i], hindi_attention_masks[i], hindi_labels[i]) for i in range(len_test + len_val, len(df_hindi_combined))]
hindi_train_text = [hindi_labels[i] for i in range(len_test + len_val, len(df_hindi_combined))]

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 5
run_training_loops_new_strategy(english_train_set, hindi_train_set, hindi_val_set, epochs=epochs, alpha=0.67)

# saving the model here to load it later on and perform error analysis.
torch.save(model, '/content/Hindi_Model_Multilingual_Trained.pt')

seed_everything()
get_validation_performance(hindi_test_set)[0]

"""## Korean dataset

For Korean dataset we need -> Korean and Turkish datasets.
"""

df_korean_super_train = pd.concat([df_korean_train, df_turkish_train])

df_korean_combined = pd.concat([df_korean_test, df_korean_val, df_korean_super_train])

korean_input_ids, korean_attention_masks, korean_labels = create_tensors_and_text(df_korean_combined, False)
korean_texts = df_korean_combined.text_input.values

seed_everything()

len_test = len(df_korean_test)
len_val = len(df_korean_val)
len_train = len(df_korean_super_train)

korean_test_set = [(korean_input_ids[i], korean_attention_masks[i], korean_labels[i]) for i in range(len_test)]
korean_test_text = [korean_labels[i] for i in range(len_test)]

korean_val_set = [(korean_input_ids[i], korean_attention_masks[i], korean_labels[i]) for i in range(len_test,len_test + len_val)]
korean_val_text = [korean_labels[i] for i in range(len_test,len_test + len_val)]

korean_train_set = [(korean_input_ids[i], korean_attention_masks[i], korean_labels[i]) for i in range(len_test + len_val, len(df_korean_combined))]
korean_train_text = [korean_labels[i] for i in range(len_test + len_val, len(df_korean_combined))]

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 25

run_training_loops_new_strategy(english_train_set, korean_train_set, korean_val_set, epochs=epochs, alpha=0.64)

seed_everything()
get_validation_performance(korean_test_set)[0]

"""## Chinese dataset

For Chinese dataset we need -> Chinese, Spanish and Korean datasets.
"""

df_chinese_super_train = pd.concat([df_chinese_train, df_korean_train, df_turkish_train])

df_chinese_combined = pd.concat([df_chinese_test, df_chinese_val, df_chinese_super_train])

chinese_input_ids, chinese_attention_masks, chinese_labels = create_tensors_and_text(df_chinese_combined, False)
chinese_texts = df_chinese_combined.text_input.values

seed_everything()

len_test = len(df_chinese_test)
len_val = len(df_chinese_val)
len_train = len(df_chinese_super_train)

chinese_test_set = [(chinese_input_ids[i], chinese_attention_masks[i], chinese_labels[i]) for i in range(len_test)]
chinese_test_text = [chinese_labels[i] for i in range(len_test)]

chinese_val_set = [(chinese_input_ids[i], chinese_attention_masks[i], chinese_labels[i]) for i in range(len_test,len_test + len_val)]
chinese_val_text = [chinese_labels[i] for i in range(len_test,len_test + len_val)]

chinese_train_set = [(chinese_input_ids[i], chinese_attention_masks[i], chinese_labels[i]) for i in range(len_test + len_val, len(df_chinese_combined))]
chinese_train_text = [chinese_labels[i] for i in range(len_test + len_val, len(df_chinese_combined))]

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 25

run_training_loops_new_strategy(english_train_set, chinese_train_set, chinese_val_set, epochs=epochs, alpha=0.2)

seed_everything()
get_validation_performance(chinese_test_set)[0]

"""## Bangla dataset

For Bangla dataset we need -> Hindi dataset.

Since, there is not bangla train set. I will combine English and Hindi for training and then, will use bangla test set
"""

df_bangla_super_train = pd.concat([df_hindi_train])

df_bangla_combined = pd.concat([df_bangla_test, df_bangla_val, df_bangla_super_train])

bangla_input_ids, bangla_attention_masks, bangla_labels = create_tensors_and_text(df_bangla_combined, False)
bangla_texts = df_bangla_combined.text_input.values

seed_everything()

len_test = len(df_bangla_test)
len_val = len(df_bangla_val)
len_train = len(df_bangla_super_train)

bangla_test_set = [(bangla_input_ids[i], bangla_attention_masks[i], bangla_labels[i]) for i in range(len_test)]
bangla_test_text = [bangla_labels[i] for i in range(len_test)]

bangla_val_set = [(bangla_input_ids[i], bangla_attention_masks[i], bangla_labels[i]) for i in range(len_test,len_test + len_val)]
bangla_val_text = [bangla_labels[i] for i in range(len_test,len_test + len_val)]

bangla_train_set = [(bangla_input_ids[i], bangla_attention_masks[i], bangla_labels[i]) for i in range(len_test + len_val, len(df_bangla_combined))]
bangla_train_text = [bangla_labels[i] for i in range(len_test + len_val, len(df_bangla_combined))]

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 25

run_training_loops_new_strategy(english_train_set,bangla_train_set, bangla_val_set, epochs=epochs, alpha=0.64)

seed_everything()
get_validation_performance(bangla_test_set)[0]

"""## Persian dataset

For Persian dataset we need -> Hindi datasets.

Since, there is not persian train set. I will combine English and Hindi for training and then, will use persian test set
"""

df_persian_super_train = pd.concat([df_hindi_train])

df_persian_combined = pd.concat([df_persian_test, df_persian_val, df_persian_super_train])

persian_input_ids, persian_attention_masks, persian_labels = create_tensors_and_text(df_persian_combined, False)
persian_texts = df_persian_combined.text_input.values

seed_everything()

len_test = len(df_persian_test)
len_val = len(df_persian_val)
len_train = len(df_persian_super_train)

persian_test_set = [(persian_input_ids[i], persian_attention_masks[i], persian_labels[i]) for i in range(len_test)]
persian_test_text = [persian_labels[i] for i in range(len_test)]

persian_val_set = [(persian_input_ids[i], persian_attention_masks[i], persian_labels[i]) for i in range(len_test,len_test + len_val)]
persian_val_text = [persian_labels[i] for i in range(len_test,len_test + len_val)]

persian_train_set = [(persian_input_ids[i], persian_attention_masks[i], persian_labels[i]) for i in range(len_test + len_val, len(df_persian_combined))]
persian_train_text = [persian_labels[i] for i in range(len_test + len_val, len(df_persian_combined))]

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 10

run_training_loops_new_strategy(english_train_set, persian_train_set, persian_val_set, epochs=epochs, alpha=0.2)

seed_everything()
get_validation_performance(persian_test_set)[0]

"""## Nepali dataset

For Nepali dataset we need -> Turkish and Hindi datasets.

Since, there is not nepali train set. I will combine English. Turkish and Hindi for training and then, will use nepali test set
"""

df_nepali_super_train = pd.concat([df_hindi_train, df_turkish_train])

df_nepali_combined = pd.concat([df_nepali_test, df_nepali_val, df_nepali_super_train])

nepali_input_ids, nepali_attention_masks, nepali_labels = create_tensors_and_text(df_nepali_combined, False)
nepali_texts = df_nepali_combined.text_input.values

seed_everything()

len_test = len(df_nepali_test)
len_val = len(df_nepali_val)
len_train = len(df_nepali_super_train)

nepali_test_set = [(nepali_input_ids[i], nepali_attention_masks[i], nepali_labels[i]) for i in range(len_test)]
nepali_test_text = [nepali_labels[i] for i in range(len_test)]

nepali_val_set = [(nepali_input_ids[i], nepali_attention_masks[i], nepali_labels[i]) for i in range(len_test,len_test + len_val)]
nepali_val_text = [nepali_labels[i] for i in range(len_test,len_test + len_val)]

nepali_train_set = [(nepali_input_ids[i], nepali_attention_masks[i], nepali_labels[i]) for i in range(len_test + len_val, len(df_nepali_combined))]
nepali_train_text = [nepali_labels[i] for i in range(len_test + len_val, len(df_nepali_combined))]

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 25
run_training_loops_new_strategy(english_train_set, nepali_train_set, nepali_val_set, epochs=epochs, alpha=0.61)

seed_everything()
get_validation_performance(nepali_test_set)[0]

"""## Turkish dataset

For Turkish dataset we need -> Turkish and Chinese datasets.
"""

df_turkish_super_train = pd.concat([df_turkish_train, df_chinese_train])

df_turkish_combined = pd.concat([df_turkish_test, df_turkish_val, df_turkish_super_train])

turkish_input_ids, turkish_attention_masks, turkish_labels = create_tensors_and_text(df_turkish_combined, False)
turkish_texts = df_turkish_combined.text_input.values

seed_everything()

len_test = len(df_turkish_test)
len_val = len(df_turkish_val)
len_train = len(df_turkish_super_train)

turkish_test_set = [(turkish_input_ids[i], turkish_attention_masks[i], turkish_labels[i]) for i in range(len_test)]
turkish_test_text = [turkish_labels[i] for i in range(len_test)]

turkish_val_set = [(turkish_input_ids[i], turkish_attention_masks[i], turkish_labels[i]) for i in range(len_test,len_test + len_val)]
turkish_val_text = [turkish_labels[i] for i in range(len_test,len_test + len_val)]

turkish_train_set = [(turkish_input_ids[i], turkish_attention_masks[i], turkish_labels[i]) for i in range(len_test + len_val, len(df_turkish_combined))]
turkish_train_text = [turkish_labels[i] for i in range(len_test + len_val, len(df_turkish_combined))]

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 20
run_training_loops_new_strategy(english_train_set, turkish_train_set, turkish_val_set, epochs=epochs, alpha=0.51)

seed_everything()
get_validation_performance(turkish_test_set)[0]

"""## Spanish dataset

For Spanish dataset we need -> Spanish, Chinese, Hindi and Korean datasets.
"""

df_spanish_super_train = pd.concat([df_spanish_train,df_chinese_train, df_hindi_train,df_korean_train  ])

df_spanish_combined = pd.concat([df_spanish_test, df_spanish_val, df_spanish_super_train])

spanish_input_ids, spanish_attention_masks, spanish_labels = create_tensors_and_text(df_spanish_combined, False)
spanish_texts = df_spanish_combined.text_input.values

seed_everything()

len_test = len(df_spanish_test)
len_val = len(df_spanish_val)
len_train = len(df_spanish_super_train)

spanish_test_set = [(spanish_input_ids[i], spanish_attention_masks[i], spanish_labels[i]) for i in range(len_test)]
spanish_test_text = [spanish_labels[i] for i in range(len_test)]

spanish_val_set = [(spanish_input_ids[i], spanish_attention_masks[i], spanish_labels[i]) for i in range(len_test,len_test + len_val)]
spanish_val_text = [spanish_labels[i] for i in range(len_test,len_test + len_val)]

spanish_train_set = [(spanish_input_ids[i], spanish_attention_masks[i], spanish_labels[i]) for i in range(len_test + len_val, len(df_spanish_combined))]
spanish_train_text = [spanish_labels[i] for i in range(len_test + len_val, len(df_spanish_combined))]

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 27
run_training_loops_new_strategy(english_train_set, turkish_train_set, turkish_val_set, epochs=epochs, alpha=0.54)

seed_everything()
get_validation_performance(spanish_test_set)[0]

"""# Error analysis

Error Analysis - Let's perform on hindi since we know the language.
We have included detailed summary of our findings of the error analysis in the report in section 3.6 Error Analysis

HINDI - Model saved and loaded.
"""

from transformers import XLMRobertaTokenizer

seed_everything()
torch.cuda.empty_cache()

# loading the model we saved earlier from experiment 5.3 with Hindi dataset
model = torch.load('/content/Hindi_Model_Multilingual_Trained.pt')
model.eval()

val_set = hindi_test_set

# Tracking variables
total_eval_accuracy = 0
total_eval_loss = 0

num_batches = int(len(val_set)/batch_size) + 1
tokenizer = XLMRobertaTokenizer.from_pretrained('xlm-roberta-base')

total_correct = 0
incorrect_predictions = []  # List to store incorrect predictions

for i in range(num_batches):

  end_index = min(batch_size * (i+1), len(val_set))
  batch = val_set[i*batch_size:end_index]

  if len(batch) == 0: continue

  input_id_tensors = torch.stack([data[0] for data in batch])
  input_mask_tensors = torch.stack([data[1] for data in batch])
  label_tensors = torch.stack([data[2] for data in batch])

  # Move tensors to the GPU
  b_input_ids = input_id_tensors.to(device)
  b_input_mask = input_mask_tensors.to(device)
  b_labels = label_tensors.to(device)

  # Tell pytorch not to bother with constructing the compute graph
  # during the forward pass
  with torch.no_grad():
    # Forward pass, calculate logit predictions.
    outputs = model(b_input_ids,
                      token_type_ids=None,
                      attention_mask=b_input_mask,
                      labels=b_labels)
    # loss = outputs.loss
    logits = outputs.logits

    # Accumulate the validation loss.
    # total_eval_loss += loss.item()

    # Move logits and labels to CPU
    logits = (logits).detach().cpu().numpy()
    label_ids = b_labels.to('cpu').numpy()

    # Calculate the number of correctly labeled examples in batch
    pred_flat = np.argmax(logits, axis=1).flatten()
    labels_flat = np.argmax(label_ids, axis=1).flatten()

    # num_correct = np.sum(pred_flat == labels_flat)
    # total_correct += num_correct

    # Analyze incorrect predictions
    incorrect_indices = np.where(pred_flat != labels_flat)[0]
    for idx in incorrect_indices:
      # Access corresponding data and predicted label
      incorrect_data = batch[idx]
      question=tokenizer.decode(incorrect_data[0], skip_special_tokens=True)
      # Split data into question and answer
      index = question.find("?")
      if index != -1:
        answer = question[index+1:]
        question= question[:index+1]
      else:
        answer=" "
      predicted_label = label_mapping[pred_flat[idx]]
      true_label = label_mapping[labels_flat[idx]]

      # Append data to incorrect predictions list
      incorrect_predictions.append((question, answer, predicted_label, true_label))



# printing the data
for question,answer, predicted_label, true_label in incorrect_predictions[:20]:
  if predicted_label == 0 : predicted_label = "Yes"
  elif predicted_label == 1 : predicted_label = "No"
  elif predicted_label == 2 : predicted_label = "Middle"

  if true_label == 0 : true_label = "Yes"
  elif true_label == 1 : true_label = "No"
  elif true_label == 2 : true_label = "Middle"

  print(f"Data: {question}")
  print(f"Answer: {answer}")
  print(f"Incorrect prediction: Predicted: {predicted_label}, True: {true_label}")
  print("-------------------------------------------------------------------------------")

"""# Part 2

<h1>Part - 2</h1>
"""

from google.colab import drive
drive.mount('/content/drive')

# FILE_PATH = './drive/MyDrive/GMU/NLP/CS678Project/data/part2'

"""## Test data annotation & agreement scores"""

### WRITE CODE TO LOAD ANNOTATIONS AND
### COMPUTE AGREEMENT + COHEN'S KAPPA HERE!
import pandas as pd
from sklearn.metrics import cohen_kappa_score

def raw_agreement(annotator1_df, annotator2_df):
    # TODO: Implement this function
    same = 0
    for i in range(len(annotator1_df)):
      if annotator1_df[i] == annotator2_df[i]:
        same += 1
    return same / len(annotator1_df)

def kohens_cappa(annotator1_df, annotator2_df):
    # TODO: Implement this function
    return cohen_kappa_score(annotator1_df, annotator2_df)
    return None

# TODO: load your data correctly
annotator1_df = pd.read_csv(f'{FILE_PATH}/data/test_dataset/Test_Noel.csv')['label']
annotator2_df = pd.read_csv(f'{FILE_PATH}/data/test_dataset/Test_Karthik.csv')['label']

print("--- Raw agreement between annotator1 and annotator2 ---")
print(raw_agreement(annotator1_df, annotator2_df))

print("--- Cohen's kappa score between annotator1 and annotator2 ---")
print(kohens_cappa(annotator1_df, annotator2_df))

"""## Recreating Experiment 5.1 Cross-Lingual Learning from English

### Italian Dataset
"""

df_italian = pd.read_csv(f'{FILE_PATH}/data/test_dataset/italian_test_dataset.csv')
df_italian = create_file(df_italian)

df_italian['label'].unique()

df_italian.head()

italian_input_ids, italian_attention_masks, italian_labels = create_tensors_and_text(df_italian, False)
italian_texts = df_italian.text_input.values

seed_everything()

total = len(df_italian)

italian_test_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(total)]

italian_test_text = [italian_labels[i] for i in range(total)]

# function to get validation f1 score - returns f1_score, validation_accuracy
from sklearn.metrics import f1_score
from sklearn.metrics import precision_recall_fscore_support

def get_validation_performance_part2(val_set):
    # Put the model in evaluation mode
    model.eval()

    # Tracking variables
    total_eval_accuracy = 0
    total_eval_loss = 0

    num_batches = int(len(val_set)/batch_size) + 1

    total_correct = 0
    # These lists will store all the predictions and true labels across batches
    all_predictions = []
    all_labels = []

    for i in range(num_batches):

      end_index = min(batch_size * (i+1), len(val_set))

      batch = val_set[i*batch_size:end_index]

      if len(batch) == 0: continue

      input_id_tensors = torch.stack([data[0] for data in batch])
      input_mask_tensors = torch.stack([data[1] for data in batch])
      label_tensors = torch.stack([data[2] for data in batch])

      # Move tensors to the GPU
      b_input_ids = input_id_tensors.to(device)
      b_input_mask = input_mask_tensors.to(device)
      b_labels = label_tensors.to(device)

      # Tell pytorch not to bother with constructing the compute graph during
      # the forward pass, since this is only needed for backprop (training).
      with torch.no_grad():

        # Forward pass, calculate logit predictions.
        # Note: this line of code might need to change depending on the model
        # the current line will work for bert-base-uncased
        # please refer to huggingface documentation for other models
        outputs = model(b_input_ids,
                                token_type_ids=None,
                                attention_mask=b_input_mask,
                                labels=b_labels)
        loss = outputs.loss
        logits = outputs.logits

        # Accumulate the validation loss.
        total_eval_loss += loss.item()

        # Move logits and labels to CPU
        logits = (logits).detach().cpu().numpy()
        label_ids = b_labels.to('cpu').numpy()


        # Calculate the number of correctly labeled examples in batch
        pred_flat = np.argmax(logits, axis=1).flatten()
        labels_flat = np.argmax(label_ids, axis=1).flatten()

        all_predictions.extend(pred_flat)
        all_labels.extend(labels_flat)

        num_correct = np.sum(pred_flat == labels_flat)
        total_correct += num_correct

    # Report the final accuracy for this validation run.
    print("Num of correct predictions =", total_correct)
    avg_val_accuracy = total_correct / len(val_set)
    # f1 = f1_score(all_labels, all_predictions, average='weighted')
    precision, recall, f1, _ = precision_recall_fscore_support(all_labels, all_predictions, average='weighted')

    return f1, avg_val_accuracy, precision, recall

seed_everything()
get_validation_performance_part2(italian_test_set)

"""```
# This is formatted as code
```

<ul>
<li>Precision: 0.3112193501371742</li>
<li>Recall: 0.5578703703703703</li>
<li>F1-Score: 0.39954460403940345</li>
<li>Accuracy: 0.5578703703703703</li>
</ul>

## Recreating Experiment 5.2 Fine-Tuning with the New Language

### Setting up the model, optimizer and training function
"""

from transformers import XLMRobertaForSequenceClassification, Trainer, TrainingArguments

model = XLMRobertaForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=3)
model.cuda()

from torch.optim import AdamW

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 30

# 0.0003

import random
import torch

def run_training_loops_new_strategy(train_set_english, train_set_other_language, val_set, epochs, alpha):
    # Assuming train_set_english and train_set_other_language are lists of tuples (input_id, attention_mask, label)
    # and alpha is the reduction factor for the other_language dataset size after each epoch.

    val_acc = 0  # Initialize validation accuracy

    for epoch_i in range(epochs):
        print(f"\n======== Epoch {epoch_i + 1} / {epochs} ========")
        print("Training...")

        # Concatenate English data with a subset of other_language data
        # Reduce the other_language dataset by alpha after each epoch
        other_language_data_size = int(len(train_set_other_language) * (alpha ** epoch_i))
        current_train_set = train_set_english + random.sample(train_set_other_language, other_language_data_size)

        total_train_loss = 0  # Reset total loss for this epoch

        model.train()  # Put the model into training mode

        num_batches = len(current_train_set) // batch_size + (len(current_train_set) % batch_size != 0)

        for i in range(num_batches):
            batch = current_train_set[i * batch_size:(i + 1) * batch_size]
            if not batch:
                continue

            b_input_ids, b_input_mask, b_labels = zip(*batch)  # Unpack batch data

            # Convert lists to tensors and move them to the device (GPU/CPU)
            b_input_ids = torch.stack(b_input_ids).to(device)
            b_input_mask = torch.stack(b_input_mask).to(device)
            b_labels = torch.stack(b_labels).to(device)

            optimizer.zero_grad()

            outputs = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask, labels=b_labels)
            loss = outputs.loss
            total_train_loss += loss.item()

            loss.backward()  # Calculate gradients
            optimizer.step()  # Update parameters

        print(f"Total loss: {total_train_loss}")
        f1,val_acc = get_validation_performance(val_set)  # Evaluate on validation set
        print(f"Validation accuracy: {val_acc}")

    print("\nTraining complete!")
    return val_acc

# Note: You would need to define `get_validation_performance`, `batch_size`, `model`, `optimizer`, and ensure that `device` is set correctly (e.g., to 'cuda' or 'cpu').
# Also, ensure that your model, optimizer, and data are correctly transferred to the GPU if you're using one.

# Lastly, saving the model after training is completed is essential for later use or further training.
# The placeholder for saving the model is already in your script, so don't forget to use it with your model's and training's specifics.

"""### Italian Dataset"""

df_italian_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/italian_test_dataset.csv')
df_italian_test = create_file(df_italian_test)

df_italian_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/italian_val_dataset.csv')
df_italian_val = create_file(df_italian_val)

df_italian_train = pd.read_csv(f'{FILE_PATH}/data/train_dataset/italian_train_dataset.csv')
df_italian_train = create_file(df_italian_train)




# df_italian_train = pd.concat([df_italian_train_yes, df_italian_train_no])

df_italian_combined = pd.concat([df_italian_test, df_italian_val, df_italian_train])

italian_input_ids, italian_attention_masks, italian_labels = create_tensors_and_text(df_italian_combined, False)
italian_texts = df_italian_combined.text_input.values

seed_everything()

len_test = len(df_italian_test)
len_val = len(df_italian_val)
len_train = len(df_italian_train)

italian_test_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test)]
italian_test_text = [italian_labels[i] for i in range(len_test)]

italian_val_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test,len_test + len_val)]
italian_val_text = [italian_labels[i] for i in range(len_test,len_test + len_val)]

italian_train_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test + len_val, len(df_italian_combined))]
italian_train_text = [italian_labels[i] for i in range(len_test + len_val, len(df_italian_combined))]

len(italian_train_set)

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 10
# experiment with alpha = 0.5 since other datasets have followed those alpha values
run_training_loops_new_strategy(english_train_set, italian_train_set, italian_val_set, epochs=epochs, alpha=0.5)

seed_everything()
get_validation_performance_part2(italian_test_set)

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 10
# experiment with alpha = 0.2 since other datasets have followed those alpha values
run_training_loops_new_strategy(english_train_set, italian_train_set, italian_val_set, epochs=epochs, alpha=0.2)

seed_everything()
get_validation_performance_part2(italian_test_set)

from transformers import XLMRobertaForSequenceClassification, Trainer, TrainingArguments

model = XLMRobertaForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=3)
model.cuda()

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 10
# experiment with alpha = 0.7 since other datasets have followed those alpha values
run_training_loops_new_strategy(english_train_set, italian_train_set, italian_val_set, epochs=epochs, alpha=0.7)

seed_everything()
get_validation_performance_part2(italian_test_set)

"""## Recreating Experiment 5.3 Fine-Tuning with Several Languages

#### Italian data loading
"""

df_italian_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/italian_test_dataset.csv')
df_italian_test = create_file(df_italian_test)

df_italian_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/italian_val_dataset.csv')
df_italian_val = create_file(df_italian_val)

df_italian_train = pd.read_csv(f'{FILE_PATH}/data/train_dataset/italian_train_dataset.csv')
df_italian_train = create_file(df_italian_train)

"""Expeimenting with English + Italian same as 5.2  + Hindi/Korean/Chinese/Turkish/Spanish

Load other language data from section Experiment 5.2 -> Data Loading
"""

# df_italian_super_train = pd.concat([df_italian_train, df_hindi_train])

# df_italian_super_train = pd.concat([df_italian_train, df_korean_train])

# df_italian_super_train = pd.concat([df_italian_train, df_chinese_train])

# df_italian_super_train = pd.concat([df_italian_train, df_turkish_train])

df_italian_super_train = pd.concat([df_italian_train, df_spanish_train])

df_italian_combined = pd.concat([df_italian_test, df_italian_val, df_italian_super_train])

italian_input_ids, italian_attention_masks, italian_labels = create_tensors_and_text(df_italian_combined, False)
italian_texts = df_italian_combined.text_input.values

seed_everything()

len_test = len(df_italian_test)
len_val = len(df_italian_val)
len_train = len(df_italian_super_train)

italian_test_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test)]
italian_test_text = [italian_labels[i] for i in range(len_test)]

italian_val_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test,len_test + len_val)]
italian_val_text = [italian_labels[i] for i in range(len_test,len_test + len_val)]

italian_train_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test + len_val, len(df_italian_combined))]
italian_train_text = [italian_labels[i] for i in range(len_test + len_val, len(df_italian_combined))]

"""make sure to start with a new model everytime."""

from transformers import XLMRobertaForSequenceClassification, Trainer, TrainingArguments

model = XLMRobertaForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=3)
model.cuda()

"""Average Alpha value across all languages = 0.6, Starting with it. May change later on if needed."""

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 2

run_training_loops_new_strategy(english_train_set, italian_train_set, italian_val_set, epochs=epochs, alpha=0.6)

seed_everything()
get_validation_performance(italian_test_set)

"""## Combining the best performing test datasets -> Spanish and Turkish

Turkish datasets.
"""

df_turkish_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/turkish_test_dataset.csv')
df_turkish_test = create_file(df_turkish_test)

df_turkish_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/turkish_dev_dataset.csv')
df_turkish_val = create_file(df_turkish_val)

df_turkish_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/turkish_cqa_yes_answer.csv')
df_turkish_train_yes = create_file(df_turkish_train_yes)

df_turkish_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/turkish_cqa_no_answer.csv')
df_turkish_train_no = create_file(df_turkish_train_no)

df_turkish_train = pd.concat([df_turkish_train_yes, df_turkish_train_no])

"""Spanish datasets."""

df_spanish_test = pd.read_csv(f'{FILE_PATH}/data/test_dataset/spanish_test_dataset.csv')
df_spanish_test = create_file(df_spanish_test)

df_spanish_val = pd.read_csv(f'{FILE_PATH}/data/test_dataset/spanish_dev_dataset.csv')
df_spanish_val = create_file(df_spanish_val)

df_spanish_train_yes = pd.read_csv(f'{FILE_PATH}/data/train_dataset/spanish_yes_answer.csv')
df_spanish_train_yes['label'] = 'y'
df_spanish_train_yes = create_file(df_spanish_train_yes)

df_spanish_train_no = pd.read_csv(f'{FILE_PATH}/data/train_dataset/spanish_no_answer.csv')
df_spanish_train_no['label'] = 'n'
df_spanish_train_no = create_file(df_spanish_train_no)

df_spanish_train = pd.concat([df_spanish_train_yes, df_spanish_train_no])



# Combination of the main language's train data (Italian) and the other languages in the blend (Turkish & Spanish)
df_italian_super_train = pd.concat([df_italian_train, df_turkish_train, df_spanish_train])

df_italian_combined = pd.concat([df_italian_test, df_italian_val, df_italian_super_train])

italian_input_ids, italian_attention_masks, italian_labels = create_tensors_and_text(df_italian_combined, False)
italian_texts = df_italian_combined.text_input.values

seed_everything()

len_test = len(df_italian_test)
len_val = len(df_italian_val)
len_train = len(df_italian_super_train)

italian_test_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test)]
italian_test_text = [italian_labels[i] for i in range(len_test)]

italian_val_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test,len_test + len_val)]
italian_val_text = [italian_labels[i] for i in range(len_test,len_test + len_val)]

italian_train_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test + len_val, len(df_italian_combined))]
italian_train_text = [italian_labels[i] for i in range(len_test + len_val, len(df_italian_combined))]

from transformers import XLMRobertaForSequenceClassification, Trainer, TrainingArguments

model = XLMRobertaForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=3)
model.cuda()

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 10
run_training_loops_new_strategy(english_train_set, italian_train_set, italian_val_set, epochs=epochs, alpha=0.67)

seed_everything()
get_validation_performance_part2(italian_test_set)

"""```
# This is formatted as code
```

<ul>
<li>Precision: 0.6984411272483598</li>
<li>Recall: 0.7013888888888888</li>
<li>F1-Score: 0.654741332897673</li>
<li>Accuracy: 0.7013888888888888</li>
</ul>

## Combining Italian with Hindi Spanish and Turkish

Load Italian, Spanish, Turkish and Hindi data from above section.
"""

# Combination of the main language's train data (Italian) and the other languages in the blend (Turkish & Spanish)
df_italian_super_train = pd.concat([df_italian_train, df_turkish_train, df_spanish_train, df_hindi_train])

df_italian_combined = pd.concat([df_italian_test, df_italian_val, df_italian_super_train])

italian_input_ids, italian_attention_masks, italian_labels = create_tensors_and_text(df_italian_combined, False)
italian_texts = df_italian_combined.text_input.values

seed_everything()

len_test = len(df_italian_test)
len_val = len(df_italian_val)
len_train = len(df_italian_super_train)

italian_test_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test)]
italian_test_text = [italian_labels[i] for i in range(len_test)]

italian_val_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test,len_test + len_val)]
italian_val_text = [italian_labels[i] for i in range(len_test,len_test + len_val)]

italian_train_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test + len_val, len(df_italian_combined))]
italian_train_text = [italian_labels[i] for i in range(len_test + len_val, len(df_italian_combined))]

from transformers import XLMRobertaForSequenceClassification, Trainer, TrainingArguments

model = XLMRobertaForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=3)
model.cuda()

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 10
run_training_loops_new_strategy(english_train_set, italian_train_set, italian_val_set, epochs=epochs, alpha=0.55)

seed_everything()
get_validation_performance_part2(italian_test_set)

"""## Combining Italian with Hindi and Turkish"""

df_italian_super_train = pd.concat([df_italian_train, df_turkish_train, df_hindi_train])

df_italian_combined = pd.concat([df_italian_test, df_italian_val, df_italian_super_train])

italian_input_ids, italian_attention_masks, italian_labels = create_tensors_and_text(df_italian_combined, False)
italian_texts = df_italian_combined.text_input.values

seed_everything()

len_test = len(df_italian_test)
len_val = len(df_italian_val)
len_train = len(df_italian_super_train)

italian_test_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test)]
italian_test_text = [italian_labels[i] for i in range(len_test)]

italian_val_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test,len_test + len_val)]
italian_val_text = [italian_labels[i] for i in range(len_test,len_test + len_val)]

italian_train_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test + len_val, len(df_italian_combined))]
italian_train_text = [italian_labels[i] for i in range(len_test + len_val, len(df_italian_combined))]

from transformers import XLMRobertaForSequenceClassification, Trainer, TrainingArguments

model = XLMRobertaForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=3)
model.cuda()

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 15
run_training_loops_new_strategy(english_train_set, italian_train_set, italian_val_set, epochs=epochs, alpha=0.65)

seed_everything()
get_validation_performance_part2(italian_test_set)

"""## Combining Italian Spanish only"""

# Combination of the main language's train data (Italian) and the other languages in the blend (Turkish & Spanish)
df_italian_super_train = pd.concat([df_italian_train, df_spanish_train])

df_italian_combined = pd.concat([df_italian_test, df_italian_val, df_italian_super_train])

italian_input_ids, italian_attention_masks, italian_labels = create_tensors_and_text(df_italian_combined, False)
italian_texts = df_italian_combined.text_input.values

seed_everything()

len_test = len(df_italian_test)
len_val = len(df_italian_val)
len_train = len(df_italian_super_train)

italian_test_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test)]
italian_test_text = [italian_labels[i] for i in range(len_test)]

italian_val_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test,len_test + len_val)]
italian_val_text = [italian_labels[i] for i in range(len_test,len_test + len_val)]

italian_train_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test + len_val, len(df_italian_combined))]
italian_train_text = [italian_labels[i] for i in range(len_test + len_val, len(df_italian_combined))]

from transformers import XLMRobertaForSequenceClassification, Trainer, TrainingArguments

model = XLMRobertaForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=3)
model.cuda()

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 10
run_training_loops_new_strategy(english_train_set, italian_train_set, italian_val_set, epochs=epochs, alpha=0.67)

seed_everything()
get_validation_performance_part2(italian_test_set)

"""```
# This is formatted as code
```

<ul>
<li>Precision: 0.6427027022913776</li>
<li>Recall: 0.6427027022913776</li>
<li>F1-Score: 0.6292668611148218</li>
<li>Accuracy: 0.6828703703703703</li>
</ul>

## Combining Italian Turkish only
"""

# Combination of the main language's train data (Italian) and the other languages in the blend (Turkish & Spanish)
df_italian_super_train = pd.concat([df_italian_train, df_turkish_train])

df_italian_combined = pd.concat([df_italian_test, df_italian_val, df_italian_super_train])

italian_input_ids, italian_attention_masks, italian_labels = create_tensors_and_text(df_italian_combined, False)
italian_texts = df_italian_combined.text_input.values

seed_everything()

len_test = len(df_italian_test)
len_val = len(df_italian_val)
len_train = len(df_italian_super_train)

italian_test_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test)]
italian_test_text = [italian_labels[i] for i in range(len_test)]

italian_val_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test,len_test + len_val)]
italian_val_text = [italian_labels[i] for i in range(len_test,len_test + len_val)]

italian_train_set = [(italian_input_ids[i], italian_attention_masks[i], italian_labels[i]) for i in range(len_test + len_val, len(df_italian_combined))]
italian_train_text = [italian_labels[i] for i in range(len_test + len_val, len(df_italian_combined))]

from transformers import XLMRobertaForSequenceClassification, Trainer, TrainingArguments

model = XLMRobertaForSequenceClassification.from_pretrained('xlm-roberta-base', num_labels=3)
model.cuda()

batch_size = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=1e-2)
epochs = 10
run_training_loops_new_strategy(english_train_set, italian_train_set, italian_val_set, epochs=epochs, alpha=0.67)

# saving the model here to load it later on and perform error analysis.
torch.save(model, '/content/Italian_Model_Multilingual_Trained.pt')

seed_everything()
get_validation_performance_part2(italian_test_set)

"""```
# This is formatted as code
```

<ul>
<li>Precision: 0.6835561513097745</li>
<li>Recall: 0.6944444444444444</li>
<li>F1-Score: 0.6853297686581499</li>
<li>Accuracy: 0.6944444444444444</li>
</ul>

## Error analysis using the best performing combination on Italian data.
"""

from transformers import XLMRobertaTokenizer

seed_everything()
torch.cuda.empty_cache()

# loading the model we saved earlier from experiment 5.3 with Hindi dataset
model = torch.load('/content/Italian_Model_Multilingual_Trained.pt')
model.eval()

val_set = italian_test_set

# Tracking variables
total_eval_accuracy = 0
total_eval_loss = 0

num_batches = int(len(val_set)/batch_size) + 1
tokenizer = XLMRobertaTokenizer.from_pretrained('xlm-roberta-base')

total_correct = 0
incorrect_predictions = []  # List to store incorrect predictions

for i in range(num_batches):

  end_index = min(batch_size * (i+1), len(val_set))
  batch = val_set[i*batch_size:end_index]

  if len(batch) == 0: continue

  input_id_tensors = torch.stack([data[0] for data in batch])
  input_mask_tensors = torch.stack([data[1] for data in batch])
  label_tensors = torch.stack([data[2] for data in batch])

  # Move tensors to the GPU
  b_input_ids = input_id_tensors.to(device)
  b_input_mask = input_mask_tensors.to(device)
  b_labels = label_tensors.to(device)

  # Tell pytorch not to bother with constructing the compute graph
  # during the forward pass
  with torch.no_grad():
    # Forward pass, calculate logit predictions.
    outputs = model(b_input_ids,
                      token_type_ids=None,
                      attention_mask=b_input_mask,
                      labels=b_labels)
    # loss = outputs.loss
    logits = outputs.logits

    # Accumulate the validation loss.
    # total_eval_loss += loss.item()

    # Move logits and labels to CPU
    logits = (logits).detach().cpu().numpy()
    label_ids = b_labels.to('cpu').numpy()

    # Calculate the number of correctly labeled examples in batch
    pred_flat = np.argmax(logits, axis=1).flatten()
    labels_flat = np.argmax(label_ids, axis=1).flatten()

    # num_correct = np.sum(pred_flat == labels_flat)
    # total_correct += num_correct

    # Analyze incorrect predictions
    incorrect_indices = np.where(pred_flat != labels_flat)[0]
    for idx in incorrect_indices:
      # Access corresponding data and predicted label
      incorrect_data = batch[idx]
      question=tokenizer.decode(incorrect_data[0], skip_special_tokens=True)
      # Split data into question and answer
      index = question.find("?")
      if index != -1:
        answer = question[index+1:]
        question= question[:index+1]
      else:
        answer=" "
      predicted_label = label_mapping[pred_flat[idx]]
      true_label = label_mapping[labels_flat[idx]]

      # Append data to incorrect predictions list
      incorrect_predictions.append((question, answer, predicted_label, true_label))



# printing the data
for question,answer, predicted_label, true_label in incorrect_predictions[41:80]:
  if predicted_label == 0 : predicted_label = "Yes"
  elif predicted_label == 1 : predicted_label = "No"
  elif predicted_label == 2 : predicted_label = "Middle"

  if true_label == 0 : true_label = "Yes"
  elif true_label == 1 : true_label = "No"
  elif true_label == 2 : true_label = "Middle"

  print(f"Data: {question}")
  print(f"Answer: {answer}")
  print(f"Incorrect prediction: Predicted: {predicted_label}, True: {true_label}")
  print("-------------------------------------------------------------------------------")

"""## Correct predictions using the best performing combination on Italian data.

This uses the same code as incorrect predictions. Only change needed is changing pred_flat != labels_flat to pred_flat == labels_flat
"""

from transformers import XLMRobertaTokenizer

seed_everything()
torch.cuda.empty_cache()

model.eval()

val_set = italian_test_set

# Tracking variables
total_eval_accuracy = 0
total_eval_loss = 0

num_batches = int(len(val_set)/batch_size) + 1
tokenizer = XLMRobertaTokenizer.from_pretrained('xlm-roberta-base')

total_correct = 0
correct_predictions = []  # List to store correct predictions

for i in range(num_batches):

  end_index = min(batch_size * (i+1), len(val_set))
  batch = val_set[i*batch_size:end_index]

  if len(batch) == 0: continue

  input_id_tensors = torch.stack([data[0] for data in batch])
  input_mask_tensors = torch.stack([data[1] for data in batch])
  label_tensors = torch.stack([data[2] for data in batch])

  # Move tensors to the GPU
  b_input_ids = input_id_tensors.to(device)
  b_input_mask = input_mask_tensors.to(device)
  b_labels = label_tensors.to(device)

  # Tell pytorch not to bother with constructing the compute graph
  # during the forward pass
  with torch.no_grad():
    # Forward pass, calculate logit predictions.
    outputs = model(b_input_ids,
                      token_type_ids=None,
                      attention_mask=b_input_mask,
                      labels=b_labels)
    # loss = outputs.loss
    logits = outputs.logits

    # Accumulate the validation loss.
    # total_eval_loss += loss.item()

    # Move logits and labels to CPU
    logits = (logits).detach().cpu().numpy()
    label_ids = b_labels.to('cpu').numpy()

    # Calculate the number of correctly labeled examples in batch
    pred_flat = np.argmax(logits, axis=1).flatten()
    labels_flat = np.argmax(label_ids, axis=1).flatten()

    # num_correct = np.sum(pred_flat == labels_flat)
    # total_correct += num_correct

    # Analyze incorrect predictions
    incorrect_indices = np.where(pred_flat == labels_flat)[0]
    for idx in incorrect_indices:
      # Access corresponding data and predicted label
      incorrect_data = batch[idx]
      question=tokenizer.decode(incorrect_data[0], skip_special_tokens=True)
      # Split data into question and answer
      index = question.find("?")
      if index != -1:
        answer = question[index+1:]
        question= question[:index+1]
      else:
        answer=" "
      predicted_label = label_mapping[pred_flat[idx]]
      true_label = label_mapping[labels_flat[idx]]

      # Append data to incorrect predictions list
      correct_predictions.append((question, answer, predicted_label, true_label))



# printing the data
for question,answer, predicted_label, true_label in correct_predictions[41:80]:
  if predicted_label == 0 : predicted_label = "Yes"
  elif predicted_label == 1 : predicted_label = "No"
  elif predicted_label == 2 : predicted_label = "Middle"

  if true_label == 0 : true_label = "Yes"
  elif true_label == 1 : true_label = "No"
  elif true_label == 2 : true_label = "Middle"

  print(f"Data: {question}")
  print(f"Answer: {answer}")
  print(f"Correct prediction: Predicted: {predicted_label}, True: {true_label}")
  print("-------------------------------------------------------------------------------")

"""## Testing the model trained on Italian data on other languages"""

model = torch.load('/content/Italian_Model_Multilingual_Trained.pt')
model.eval()

"""### Hindi"""

df_hindi = pd.read_csv(f'{FILE_PATH}/data/test_dataset/hindi_test_dataset.csv')
df_hindi = create_file(df_hindi)

df_hindi.head()

hindi_input_ids, hindi_attention_masks, hindi_labels = create_tensors_and_text(df_hindi, False)
hindi_texts = df_hindi.text_input.values

seed_everything()

total = len(df_hindi)

hindi_test_set = [(hindi_input_ids[i], hindi_attention_masks[i], hindi_labels[i]) for i in range(total)]

hindi_test_text = [hindi_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(hindi_test_set)[0]

"""### Korean"""

# Korean

df_korean = pd.read_csv(f'{FILE_PATH}/data/test_dataset/korean_test_dataset.csv')
df_korean = create_file(df_korean)

korean_input_ids, korean_attention_masks, korean_labels = create_tensors_and_text(df_korean, False)
korean_texts = df_korean.text_input.values

seed_everything()

total = len(df_korean)

korean_test_set = [(korean_input_ids[i], korean_attention_masks[i], korean_labels[i]) for i in range(total)]

korean_test_text = [korean_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(korean_test_set)[0]

"""### Chinese"""

# chinese

df_chinese = pd.read_csv(f'{FILE_PATH}/data/test_dataset/chinese_test_dataset.csv')
df_chinese = create_file(df_chinese)

chinese_input_ids, chinese_attention_masks, chinese_labels = create_tensors_and_text(df_chinese, False)
chinese_texts = df_chinese.text_input.values

seed_everything()

total = len(df_chinese)

chinese_test_set = [(chinese_input_ids[i], chinese_attention_masks[i], chinese_labels[i]) for i in range(total)]

chinese_test_text = [chinese_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(chinese_test_set)[0]

"""### Bangla"""

# bangla

df_bangla = pd.read_csv(f'{FILE_PATH}/data/test_dataset/bangla_test_dataset.csv')
df_bangla = create_file(df_bangla)

bangla_input_ids, bangla_attention_masks, bangla_labels = create_tensors_and_text(df_bangla, False)
bangla_texts = df_bangla.text_input.values

seed_everything()

total = len(df_bangla)

bangla_test_set = [(bangla_input_ids[i], bangla_attention_masks[i], bangla_labels[i]) for i in range(total)]

bangla_test_text = [bangla_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(bangla_test_set)[0]

"""### Turkish"""

# turkish

df_turkish = pd.read_csv(f'{FILE_PATH}/data/test_dataset/turkish_test_dataset.csv')
df_turkish = create_file(df_turkish)

turkish_input_ids, turkish_attention_masks, turkish_labels = create_tensors_and_text(df_turkish, False)
turkish_texts = df_turkish.text_input.values

seed_everything()

total = len(df_turkish)

turkish_test_set = [(turkish_input_ids[i], turkish_attention_masks[i], turkish_labels[i]) for i in range(total)]

turkish_test_text = [turkish_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(turkish_test_set)[0]

"""### Spanish"""

# spanish

df_spanish = pd.read_csv(f'{FILE_PATH}/data/test_dataset/spanish_test_dataset.csv')
df_spanish = create_file(df_spanish)

spanish_input_ids, spanish_attention_masks, spanish_labels = create_tensors_and_text(df_spanish, False)
spanish_texts = df_spanish.text_input.values

seed_everything()

total = len(df_spanish)

spanish_test_set = [(spanish_input_ids[i], spanish_attention_masks[i], spanish_labels[i]) for i in range(total)]

spanish_test_text = [spanish_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(spanish_test_set)[0]

"""### Nepali"""

# nepali

df_nepali = pd.read_csv(f'{FILE_PATH}/data/test_dataset/nepali_test_dataset.csv')
df_nepali = create_file(df_nepali)

nepali_input_ids, nepali_attention_masks, nepali_labels = create_tensors_and_text(df_nepali, False)
nepali_texts = df_nepali.text_input.values

seed_everything()

total = len(df_nepali)

nepali_test_set = [(nepali_input_ids[i], nepali_attention_masks[i], nepali_labels[i]) for i in range(total)]

nepali_test_text = [nepali_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(nepali_test_set)[0]

"""### Persian"""

# persian

df_persian = pd.read_csv(f'{FILE_PATH}/data/test_dataset/persian_test_dataset.csv')
df_persian = create_file(df_persian)

persian_input_ids, persian_attention_masks, persian_labels = create_tensors_and_text(df_persian, False)
persian_texts = df_persian.text_input.values

seed_everything()

total = len(df_persian)

persian_test_set = [(persian_input_ids[i], persian_attention_masks[i], persian_labels[i]) for i in range(total)]

persian_test_text = [persian_labels[i] for i in range(total)]

seed_everything()
get_validation_performance(persian_test_set)[0]